name: Parallel commands
description: Run a bunch of commands in parallel, return the first error encountered
inputs:
  commands:
    description: A comma-separated list of commands (and their arguments)
    required: true
  working-directory:
    description: The root directory to execute commands from
    required: false
runs:
  using: node16
  main: dist/index.js
