name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Parallel command tests
        uses: bewica/parallel-commands@v0.7.1
        with:
          commands: |
            echo hello \
              this is a test,
            sleep 3; echo bye,
            sleep 1; echo exiting; exit 0,
            mkdir -p test/apple; cd test/apple; echo $PWD,
            mkdir -p test2/pear; cd test2/pear; echo $PWD,
