name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: bewica/parallel-commands@v0.6
        with:
          commands: "echo hello, sleep 3; echo bye, sleep 1; echo exiting; exit 123"
