name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Hello world action step
        id: hello
        uses: ./
        with:
          commands: |
            echo hello; \
            sleep 3; \
            echo bye

            sleep 1; \
            echo exiting

            sleep 2;
            echo good evening
