name: test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: bewica/parallel-commands@v0.5
        with:
          commands: "echo hello, sleep 2; echo bye"
